const fs=require('fs'),vm=require('vm'),assert=require('assert'),{stripTypeScriptTypes}=require('node:module');
let src=fs.readFileSync(require('node:path').join(__dirname, '../worker/index.ts'),'utf8').replace(/^import .*;$/gm,'').replace('export default appWorker;','globalThis.test={appWorker,REPORTS,BUILDINGS,reportWorkspaceHtml,reportGeneratorHtml,clientRecords,generateReport,validateTaxWorkpaper,taxWorkpaperSnapshot,evidenceLocationHtml,clientUploadCard,facilityDatabase,facilityDatabaseHtml};');const stored=new Map(),meta=new Map();let aiCalls=0,lastPrompt='';const visual={updatedAt:'2026-10-10',consolidatedInventory:[{inventoryId:'INV-BLDG001-DOOR',room:'Lobby',visibleName:'Door',quantity:2,confidence:0.87,geometryLengthRangeFeet:[2,4],evidenceSweepIds:['real-sweep','second-sweep']}]};
const bucket={put:async(k,v,options)=>{if(options?.onlyIf){const current=stored.has(k)?String(stored.get(k)):null;if(options.onlyIf.etagMatches&&options.onlyIf.etagMatches!==current)return null;if(options.onlyIf.etagDoesNotMatch==='*'&&current!==null)return null;}stored.set(k,typeof v==='string'?v:await new Response(v).arrayBuffer());meta.set(k,options?.customMetadata||{});return {etag:String(stored.get(k))}},get:async k=>{const v=stored.get(k);return v===undefined?null:{body:v,etag:String(v),json:async()=>JSON.parse(v)}},list:async({prefix,limit})=>({objects:[...stored.keys()].filter(k=>k.startsWith(prefix)).sort().slice(0,limit||1000).map(key=>({key,customMetadata:meta.get(key)})),truncated:false})};
const ctx={Response,Request,URL,crypto,console,process:{env:{}},File,FormData,loadPersistedVisualEvidence:async()=>visual,loadPersistedGeometryEvidence:async()=>({objPresent:true}),loadGeometryAnalysis:async()=>({algorithmVersion:'test-geometry'}),fetch:async(u,init)=>{aiCalls++;lastPrompt=JSON.parse(init.body).input[0].content[0].text;return Response.json({output_text:JSON.stringify({summary:'Test report',limitations:['Verify'],rows:[{cells:['Lobby','Door','2','Count','OBJ','Verify'],classification:'OBSERVED',confidence:80,evidenceSweepIds:['real-sweep','fake-sweep']}]})})}};vm.createContext(ctx);vm.runInContext(stripTypeScriptTypes(src),ctx);const {appWorker,REPORTS,BUILDINGS}=ctx.test,env={BUILDING_DATA:bucket,OPENAI_API_KEY:'test',MATTERPORT_SDK_KEY:'test'};
function scripts(html){for(const m of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1])}
async function page(path){const r=await appWorker.fetch(new Request('https://example.com'+path),env);assert.equal(r.status,200,path);const html=await r.text();scripts(html);assert(html.includes('aria-label="Breadcrumb"'));const links=[...html.matchAll(/<a[^>]*href="([^"]*\/ingest|\/evidence\/update)"[^>]*>/g)];assert.equal(links.length,1,path+' footer-only update link');assert(html.indexOf(links[0][0])>html.indexOf('<footer'));return html}
require('node:test')('building report library workflow', async()=>{
assert.equal(REPORTS.length,11);assert(REPORTS.some(r=>r.slug==='facility-inspection'));assert(REPORTS.some(r=>r.slug==='cost-segregation'));await page('/');for(const slug of ['crc','bell','vues']){const landing=await page('/'+slug);assert(landing.includes('Ask Building GPT'));assert(!landing.includes('Ask GBI'));const dbPage=await page('/'+slug+'/database');assert(dbPage.includes('Save to building knowledge'));assert(dbPage.includes('Full Building Database'));assert(!landing.includes('Report Generator</a>'));await page('/'+slug+'/evidence');const ingest=await page('/'+slug+'/ingest');assert(ingest.includes('clientRecordsForm'));assert(!ingest.includes('id="floorPlanImg"'));const generator=await page('/'+slug+'/reports');assert(generator.includes('Create only the reports you need'));for(const def of REPORTS){const html=await page('/'+slug+'/reports/'+def.slug);assert(html.includes('method:regenerate?"POST":"GET"'));assert(html.includes('history.replaceState'));assert(!html.includes('<h2>Evidence library'));}}
assert.equal(aiCalls,0,'Opening pages never generates reports');
let r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/quantity-takeoff'),env);assert.equal(r.status,404);
const data=new FormData();data.set('title','Original drawings');data.set('source','Owner');data.set('summary','Door was replaced in 2024.');data.set('file',new File(['PDF bytes'],'drawing.pdf',{type:'application/pdf'}));r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/client-records',{method:'POST',body:data}),env);assert.equal(r.status,201);const upload=await r.json();
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/quantity-takeoff',{method:'POST'}),env);assert.equal(r.status,201);const one=(await r.json()).study;assert.equal(aiCalls,1);assert(lastPrompt.includes('Door was replaced in 2024'));assert(lastPrompt.includes('contentsNotExtracted'));assert.deepEqual(one.rows[0].evidenceSweepIds,['real-sweep']);assert.equal(one.evidenceBasis.clientRecordIds.length,1);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/quantity-takeoff'),env);assert.equal((await r.json()).study.versionId,one.versionId);assert.equal(aiCalls,1,'GET reuses saved report');
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/quantity-takeoff',{method:'POST'}),env);assert.equal(r.status,201);const two=(await r.json()).study;assert.notEqual(one.versionId,two.versionId);r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports'),env);assert.equal((await r.json()).versions.length,2);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/quantity-takeoff?version='+one.versionId),env);assert.equal((await r.json()).study.versionId,one.versionId);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-002/reports/quantity-takeoff?version='+one.versionId),env);assert.equal(r.status,404);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/client-records/'+upload.id+'/file'),env);assert.equal(r.status,200);assert.equal(await r.text(),'PDF bytes');r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-002/client-records/'+upload.id+'/file'),env);assert.equal(r.status,404);
// Evidence updates preserve report snapshots and historical file versions.
const changes=new FormData();changes.set('title','Corrected drawings');changes.set('source','Owner');changes.set('summary','Door replaced in 2025, corrected.');changes.set('versionId',upload.versionId);changes.set('file',new File(['new PDF'],'new.pdf'));
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/client-records/'+upload.id,{method:'PUT',body:changes}),env);assert.equal(r.status,200);const edited=await r.json();assert.notEqual(edited.versionId,upload.versionId);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/client-records/'+upload.id,{method:'PUT',body:changes}),env);assert.equal(r.status,409,'Stale updates must not overwrite');
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/client-records'),env);const currentRecords=(await r.json()).records;assert.equal(currentRecords.length,1);assert.equal(currentRecords[0].summary,'Door replaced in 2025, corrected.');
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/client-records/'+upload.id+'/history'),env);assert.equal((await r.json()).versions.length,2);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/client-records/'+upload.id+'/file?version='+upload.versionId),env);assert.equal(await r.text(),'PDF bytes');
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/client-records/'+upload.id+'/file'),env);assert.equal(await r.text(),'new PDF');
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/quantity-takeoff?version='+one.versionId),env);assert.equal((await r.json()).study.evidenceBasis.clientRecordVersions[0].versionId,upload.versionId);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/facility-inspection',{method:'POST'}),env);const facility=(await r.json()).study;assert.equal(facility.rows[0].cells.length,9);assert(lastPrompt.includes('resolution unknown'));assert(lastPrompt.includes('Before closing'));assert.equal(facility.evidenceBasis.clientRecordVersions[0].versionId,edited.versionId);
const tax={totalBasis:120000,landBasis:20000,preparedBy:'Test CPA',assets:[{id:'A1',description:'Building',basis:100000,priorDepreciation:10000,placedInService:'2025-06-01',recoveryPeriod:'39 years',method:'Straight-line',convention:'Mid-month',source:'Closing statement / CPA allocation'}],schedule:[{assetId:'A1',year:2026,regular:2500,bonus:0,section179:0}]};
const workpaper=ctx.test.validateTaxWorkpaper(tax);assert.equal(workpaper.allocatedBasis,100000);assert.equal(workpaper.schedule[0].total,2500);
assert.throws(()=>ctx.test.validateTaxWorkpaper({...tax,totalBasis:130000}),/reconcile/);
assert.throws(()=>ctx.test.validateTaxWorkpaper({...tax,schedule:[{assetId:'A1',year:2026,regular:95000}]}),/exceed/);
assert.throws(()=>ctx.test.validateTaxWorkpaper({...tax,schedule:[tax.schedule[0],tax.schedule[0]]}),/unique/);
assert.throws(()=>ctx.test.validateTaxWorkpaper({...tax,schedule:[{assetId:'bad',year:2026,regular:1}]}),/known asset/);
assert.equal(ctx.test.taxWorkpaperSnapshot([]).assets,undefined,'Missing tax basis must stay missing');
const taxForm=new FormData();taxForm.set('title','CPA workpaper');taxForm.set('source','CPA');taxForm.set('summary','Tax allocations and deductions');taxForm.set('taxWorkpaper',JSON.stringify(tax));
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/client-records',{method:'POST',body:taxForm}),env);assert.equal(r.status,201);const taxSaved=await r.json();const snapshot=ctx.test.taxWorkpaperSnapshot(await ctx.test.clientRecords(BUILDINGS['BLDG-001'],env));assert.equal(snapshot.recordVersionId,taxSaved.versionId);assert.equal(snapshot.schedule[0].regular,2500);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/cost-segregation',{method:'POST'}),env);assert.equal(r.status,201);const cpaReport=(await r.json()).study;assert.equal(cpaReport.taxWorkpaper.recordVersionId,taxSaved.versionId);assert.equal(cpaReport.taxWorkpaper.schedule[0].total,2500);assert.equal(cpaReport.totalReplacementCostLow,null,'Missing estimate cannot become zero');
const evidenceHtml=ctx.test.evidenceLocationHtml(BUILDINGS['BLDG-001'],'test');assert(evidenceHtml.indexOf('Upload More Evidence')<evidenceHtml.indexOf('id="mp"'));assert(evidenceHtml.includes('evidencePanos'));assert(evidenceHtml.includes('showMoreAssets'));
const evidenceElements={},evidenceElement=id=>evidenceElements[id]??={textContent:'',innerHTML:'',hidden:false,src:'',value:'',files:[],reset(){},scrollIntoView(){}};
const evidenceContext={document:{getElementById:evidenceElement},window:{addEventListener(){},dispatchEvent(){}},Event,URLSearchParams,location:{search:''},Set,FormData,encodeURIComponent,setTimeout,fetch:async url=>Response.json(url.endsWith('/client-records')?{records:Array.from({length:12},(_,i)=>({id:'record-'+i,title:'Record '+i,summary:'Saved summary',source:'Owner'}))}:{completeness:{processed:40,expected:50,percent:80},geometry:{objPresent:true,objFileName:'model.obj'},geometryAnalysis:{footprintHullAreaFt2:1000},visualInventory:{analyzedSweepIds:['a','b']},floorPlanUrl:'/plan.svg',assetManifest:{categories:{panorama:Array.from({length:25},(_,i)=>({name:'pano-'+i,key:'pano-'+i,size:10}))}}})};
vm.createContext(evidenceContext);const evidenceScripts=[...evidenceHtml.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);vm.runInContext(evidenceScripts[0],evidenceContext);vm.runInContext(evidenceScripts[1],evidenceContext);await new Promise(resolve=>setImmediate(resolve));assert.equal((evidenceElement('assetRows').innerHTML.match(/<tr>/g)||[]).length,10);evidenceElement('showMoreAssets').onclick();assert.equal((evidenceElement('assetRows').innerHTML.match(/<tr>/g)||[]).length,20);evidenceElement('showMoreAssets').onclick();assert.equal((evidenceElement('assetRows').innerHTML.match(/<tr>/g)||[]).length,25);evidenceElement('showMoreAssets').onclick();assert.equal((evidenceElement('assetRows').innerHTML.match(/<tr>/g)||[]).length,10);assert.equal(evidenceElement('evidencePanos').textContent,'40 / 50');assert.equal(evidenceElement('evidenceObj').textContent,'Supplied');assert.equal((evidenceElement('editableRecords').innerHTML.match(/<article>/g)||[]).length,5);evidenceElement('showMoreRecords').onclick();assert.equal((evidenceElement('editableRecords').innerHTML.match(/<article>/g)||[]).length,10);
console.log('PASS: top upload form, restored evidence status boxes, compact file and client-record lists, show-more and show-less behavior.');
const costHtml=ctx.test.reportWorkspaceHtml(BUILDINGS['BLDG-001'],REPORTS.find(r=>r.slug==='cost-segregation'),'test');const costScript=costHtml.match(/<script type="module">([\s\S]*?)<\/script>/)[1];assert(costScript.includes('renderTaxWorkpaper'));assert(costScript.includes('Prior depreciation'));assert(costScript.includes('Annual total'));const splitCode=costScript.slice(costScript.indexOf('const taxRows='),costScript.indexOf('async function loadTaxInputs'));const splitContext={};vm.createContext(splitContext);vm.runInContext(splitCode+';globalThis.parsed=taxRows('+JSON.stringify("A1\tBuilding\t100000\nA2\tDesk\t100")+');',splitContext);assert.equal(splitContext.parsed.length,2);assert.equal(splitContext.parsed[0][1],'Building');
console.log('PASS: editable evidence, stale-write rejection, historical files, fixed report provenance, defect-first inspection prompts, CPA allocation reconciliation, schedule validation and spreadsheet parsing.');
r=await appWorker.fetch(new Request('https://example.com/crc/cost-seg'),env);assert.equal(r.status,302);assert(r.headers.get('location').endsWith('/crc/reports/cost-segregation'));
// Database is authoritative, building-scoped, versioned and read by GPT and all report outputs.
const inventoryApi='https://example.com/api/buildings/BLDG-001/inventory';
r=await appWorker.fetch(new Request(inventoryApi),env);const initialDb=await r.json();assert.equal(initialDb.assets.length,1);assert.equal(initialDb.assets[0].quantity,2);assert.equal(initialDb.assets[0].versionId,null);assert.equal(initialDb.assets[0].confidence,87);assert(initialDb.assets[0].dimensions.includes('2–4 ft'));
const correction={id:'INV-BLDG001-DOOR',versionId:null,name:'Lobby doors',location:'Lobby',category:'Doors',quantity:3,dimensions:'Door panel',length:7,width:3,height:0.2,dimensionUnit:'ft',dimensionSource:'Owner tape measurement',confidence:90,estimatedValueLow:1200,estimatedValueHigh:1800,valuationSource:'Contractor allowance',valuationDate:'2026-10-10',valueConfidence:80,make:'',model:'',serial:'',condition:'Repaired',source:'Owner field check',sourceDate:'2026-10-10',notes:'Corrected count after owner visit',reviewStatus:'Client reviewed',sourceRecordIds:[upload.id]};
r=await appWorker.fetch(new Request(inventoryApi,{method:'POST',body:JSON.stringify(correction)}),env);assert.equal(r.status,201);const asset1=(await r.json()).asset;
r=await appWorker.fetch(new Request(inventoryApi,{method:'POST',body:JSON.stringify(correction)}),env);assert.equal(r.status,409,'Stale asset edits reject');
r=await appWorker.fetch(new Request(inventoryApi),env);const correctedDb=await r.json();assert.equal(correctedDb.assets.length,1,'Correction replaces asset instead of adding duplicate');assert.equal(correctedDb.assets[0].quantity,3);assert.equal(correctedDb.assets[0].scanEvidence.quantity,2,'Original scan provenance remains available');assert.equal(visual.consolidatedInventory[0].quantity,2,'Client correction never mutates the scan');
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-002/inventory',{method:'POST',body:JSON.stringify({...correction,sourceRecordIds:[upload.id]})}),env);assert.equal(r.status,400,'Cross-building evidence links reject');
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/ask',{method:'POST',body:JSON.stringify({question:'How many lobby doors do we have?'})}),env);assert.equal(r.status,200);assert(lastPrompt.includes('Owner field check'));assert(lastPrompt.includes('Corrected count after owner visit'));assert(lastPrompt.includes('Client reviewed records are client attestations'));assert(lastPrompt.includes('Door replaced in 2025, corrected.'));
const beforeInventoryReportCalls=aiCalls;r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/insurance-inventory',{method:'POST'}),env);assert.equal(r.status,201);const inventoryReport=(await r.json()).study;assert.equal(aiCalls,beforeInventoryReportCalls,'Inventory report exports database without AI reconstruction');assert.equal(inventoryReport.rows[0].cells[1],'Lobby doors');assert(inventoryReport.rows[0].cells[2].startsWith('3'));assert.equal(inventoryReport.evidenceBasis.assetVersions[0].versionId,asset1.versionId);
r=await appWorker.fetch(new Request(inventoryApi,{method:'POST',body:JSON.stringify({...correction,versionId:asset1.versionId,quantity:4})}),env);assert.equal(r.status,201);const asset2=(await r.json()).asset;
r=await appWorker.fetch(new Request(inventoryApi+'/'+encodeURIComponent(asset1.id)+'/history'),env);assert.equal((await r.json()).versions.length,2);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/insurance-inventory?version='+inventoryReport.versionId),env);assert((await r.json()).study.rows[0].cells[2].startsWith('3'),'Saved reports keep old database snapshot');
r=await appWorker.fetch(new Request(inventoryApi,{method:'POST',body:JSON.stringify({...correction,id:undefined,versionId:undefined,name:'Boiler',quantity:'',sourceRecordIds:[]})}),env);assert.equal(r.status,201);const addedAsset=(await r.json()).asset;assert.equal(addedAsset.quantity,null,'Unknown quantity remains unknown');
r=await appWorker.fetch(new Request(inventoryApi,{method:'POST',body:JSON.stringify({...correction,versionId:asset2.versionId,reviewStatus:'Retired'})}),env);assert.equal(r.status,201);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/insurance-inventory',{method:'POST'}),env);const retiredReport=(await r.json()).study;assert.equal(retiredReport.rows.length,1);assert.equal(retiredReport.rows[0].cells[1],'Boiler','Retired asset omitted from active inventory output');
// Dimensions, value ranges and estimate confidence persist independently of scan confidence.
assert.equal(correctedDb.assets[0].width,3);assert.equal(correctedDb.assets[0].estimatedValueHigh,1800);assert.equal(inventoryReport.facilityDatabaseSnapshot[0].dimensionSource,'Owner tape measurement');assert(inventoryReport.rows[0].cells[2].includes('W 3 ft'));assert(inventoryReport.rows[0].cells[4].includes('USD 1200–1800'));
r=await appWorker.fetch(new Request(inventoryApi,{method:'POST',body:JSON.stringify({...correction,versionId:asset2.versionId,confidence:101})}),env);assert.equal(r.status,400);
r=await appWorker.fetch(new Request(inventoryApi,{method:'POST',body:JSON.stringify({...correction,versionId:asset2.versionId,dimensionSource:''})}),env);assert.equal(r.status,400);
r=await appWorker.fetch(new Request(inventoryApi,{method:'POST',body:JSON.stringify({...correction,versionId:asset2.versionId,estimatedValueHigh:100})}),env);assert.equal(r.status,400);
r=await appWorker.fetch(new Request(inventoryApi+'/'+encodeURIComponent(addedAsset.id)+'/estimate',{method:'POST',body:JSON.stringify({versionId:addedAsset.versionId})}),env);assert.equal(r.status,400,'Unknown quantities cannot create a total value');
r=await appWorker.fetch(new Request(inventoryApi,{method:'POST',body:JSON.stringify({...addedAsset,quantity:1,confidence:85,length:4,width:2,height:6,dimensionSource:'Manufacturer data',estimatedValueLow:null,estimatedValueHigh:null})}),env);assert.equal(r.status,201);const valuedBase=(await r.json()).asset;
const reportFetch=ctx.fetch;ctx.fetch=async(url,init)=>{lastPrompt=JSON.parse(init.body).input[0].content[0].text;return Response.json({output_text:JSON.stringify({low:2000,high:4000,confidence:70})})};
r=await appWorker.fetch(new Request(inventoryApi+'/'+encodeURIComponent(addedAsset.id)+'/estimate',{method:'POST',body:JSON.stringify({versionId:valuedBase.versionId})}),env);assert.equal(r.status,201);const valued=(await r.json()).asset;assert.equal(valued.estimatedValueLow,2000);assert.equal(valued.valueConfidence,70);assert.equal(valued.confidence,85);assert.equal(valued.width,2);assert(valued.valuationSource.startsWith('AI screening'));assert(lastPrompt.includes('TOTAL quantity'));
ctx.fetch=async()=>Response.json({output_text:JSON.stringify({low:null,high:null,confidence:20})});r=await appWorker.fetch(new Request(inventoryApi+'/'+encodeURIComponent(addedAsset.id)+'/estimate',{method:'POST',body:JSON.stringify({versionId:valued.versionId})}),env);assert.equal(r.status,422,'Invalid estimate must not overwrite existing value');ctx.fetch=reportFetch;
const dbUiHtml=ctx.test.facilityDatabaseHtml(BUILDINGS['BLDG-001'],'test');assert(dbUiHtml.indexOf('Facility inventory')<dbUiHtml.indexOf('Building knowledge & client records'));assert(dbUiHtml.includes('Asset dimensions'));assert(dbUiHtml.includes('Estimated replacement value'));
let dbUiScript=dbUiHtml.match(/<script>([\s\S]*?)<\/script>/)[1];const connectStart=dbUiScript.indexOf('async function connectAssetModel()'),connectEnd=dbUiScript.indexOf('async function openAssetEvidence',connectStart);dbUiScript=dbUiScript.slice(0,connectStart)+'async function connectAssetModel(){globalThis.connections++;return globalThis.mockSdk;}\n'+dbUiScript.slice(connectEnd);dbUiScript+=';globalThis.ui={refreshDatabase,openAssetEvidence};';
const dbUiElements={},dbElem=id=>dbUiElements[id]??={innerHTML:'',textContent:'',hidden:true,value:'',scrollIntoView(){},reset(){}};const moves=[];const dbUiContext={document:{getElementById:dbElem},Intl,encodeURIComponent,connections:0,mockSdk:{Sweep:{Transition:{INSTANT:'instant'},moveTo:async sweep=>moves.push(sweep)}},fetch:async()=>Response.json(correctedDb)};vm.createContext(dbUiContext);vm.runInContext(dbUiScript,dbUiContext);await dbUiContext.ui.refreshDatabase();assert(dbElem('facilityRows').innerHTML.includes('W 3 ft'));assert(dbElem('facilityRows').innerHTML.includes('90%'));assert(!dbElem('facilityRows').innerHTML.includes('need review'));assert(dbElem('facilityRows').innerHTML.includes('View 2'));await dbUiContext.ui.openAssetEvidence(correction.id,'real-sweep');assert.equal(dbElem('assetEvidenceViewer').hidden,false);await dbUiContext.ui.openAssetEvidence(correction.id,'second-sweep');assert.deepEqual(moves,['real-sweep','second-sweep']);assert.equal(dbUiContext.connections,1,'Viewer reuses one embedded model');dbElem('closeAssetViewer').onclick();assert.equal(dbElem('assetEvidenceViewer').hidden,true);
const orderDb=await ctx.test.facilityDatabase(BUILDINGS['BLDG-001'],env,{consolidatedInventory:[{inventoryId:'Z',room:'Alpha',visibleName:'A',quantity:1},{inventoryId:'A',room:'Alpha',visibleName:'Z',quantity:1},{inventoryId:'0',room:'Zulu',visibleName:'0',quantity:1}]},[]);assert.deepEqual(Array.from(orderDb.assets.filter(a=>['Z','A','0'].includes(a.id)),a=>a.id),['A','Z','0'],'Room then asset-ID ordering');
console.log('PASS: dimensions and estimated values preserved, separate value confidence, value estimation validation, room/ID sorting, all panorama buttons and embedded viewer reuse.');
console.log('PASS: database page scripts, client asset corrections without double-counting, preserved scan facts, source isolation, optimistic revisions, GPT ingestion, deterministic inventory reports, saved snapshots and retired assets.');
async function browserLoad(searchString,mode){
 const elements={};const elem=id=>elements[id]??={textContent:'',innerHTML:'',value:'',rows:[],addEventListener(){},querySelectorAll:()=>[]};let posts=0,gets=0,replaced=false;
 const context={document:{getElementById:elem,querySelectorAll:()=>[]},window:{},location:{search:searchString,pathname:'/crc/reports/quantity-takeoff'},history:{replaceState(){replaced=true}},URLSearchParams,URL,Blob,Intl,Set,AbortController,Date,setInterval:()=>1,clearInterval(){},setTimeout:()=>1,clearTimeout(){},fetch:async(u,init)=>{if(u.endsWith('/evidence'))return Response.json({visualInventory:visual});if(init?.method==='POST'){posts++;return Response.json({study:two})}gets++;return mode==='empty'?Response.json({error:'No saved report'},{status:404}):Response.json({study:one})}};
 const html=ctx.test.reportWorkspaceHtml(BUILDINGS['BLDG-001'],REPORTS.find(d=>d.slug==='quantity-takeoff'),'test');const script=html.match(/<script type="module">([\s\S]*?)<\/script>/)[1].replace('load(createRequested);','globalThis.pending=load(createRequested);');vm.createContext(context);vm.runInContext(script,context);await context.pending;
 return {posts,gets,replaced,elements};
}
async function generatorButtons(versions,fail=false){
 const views=REPORTS.map(r=>({dataset:{view:r.slug},disabled:true})),creates=REPORTS.map(r=>({dataset:{create:r.slug}}));const elements={reportLibrary:{innerHTML:''},libraryStatus:{textContent:''}};let posts=0;
 const context={document:{getElementById:id=>elements[id],querySelectorAll:sel=>sel==='[data-view]'?views:creates},window:{addEventListener(){}},location:{href:''},Map,encodeURIComponent,fetch:async(url,options)=>{if(options?.method==='POST')posts++;if(fail)throw Error('offline');return Response.json({versions})}};
 const html=ctx.test.reportGeneratorHtml(BUILDINGS['BLDG-001']);assert.equal((html.match(/data-view="[a-z-]+" disabled/g)||[]).length,REPORTS.length);const script=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace('});refresh();','});globalThis.pending=refresh();');vm.createContext(context);vm.runInContext(script,context);await context.pending;return {views,creates,context,posts};
}
const savedButtons=await generatorButtons([{reportType:'quantity-takeoff',createdAt:'2026-10-10',versionId:'v1'}]);const available=savedButtons.views.find(v=>v.dataset.view==='quantity-takeoff');assert.equal(available.disabled,false);assert(savedButtons.views.filter(v=>v!==available).every(v=>v.disabled));available.onclick();assert.equal(savedButtons.context.location.href,'/crc/reports/quantity-takeoff');assert(!savedButtons.context.location.href.includes('create=1'));const emptyButtons=await generatorButtons([]);assert(emptyButtons.views.every(v=>v.disabled));emptyButtons.views[0].onclick();assert.equal(emptyButtons.context.location.href,'');const failedButtons=await generatorButtons([],true);assert(failedButtons.views.every(v=>v.disabled));assert.equal(savedButtons.posts+emptyButtons.posts+failedButtons.posts,0);console.log('PASS: existing-report buttons enable only for saved types, remain disabled for missing/unavailable reports, and open saved workspace without generation.');
const cached=await browserLoad('','saved');assert.equal(cached.posts,0);assert.equal(cached.gets,1);assert(cached.elements.adjusterRows.innerHTML.includes('Lobby'));const empty=await browserLoad('','empty');assert.equal(empty.posts,0);assert(empty.elements.statusText.textContent.includes('No report saved'));const created=await browserLoad('?create=1','saved');assert.equal(created.posts,1);assert.equal(created.gets,0);assert(created.replaced);console.log('PASS: browser flow loads saved reports without generation, leaves empty workspaces idle, creates only explicitly selected report, and removes create flag before refresh.');
console.log('PASS: all 3 buildings and 11 report workspaces, generated scripts, footer-only updates, on-demand generation, saved report reuse, version retention, building isolation, client file/summary persistence and evidence provenance.');});
