const fs=require('fs'),vm=require('vm'),assert=require('assert'),{stripTypeScriptTypes}=require('node:module');
let src=fs.readFileSync(require('node:path').join(__dirname, '../worker/index.ts'),'utf8').replace(/^import .*;$/gm,'').replace('export default appWorker;','globalThis.test={appWorker,REPORTS,BUILDINGS,reportWorkspaceHtml,reportGeneratorHtml,clientRecords,generateReport};');const stored=new Map(),meta=new Map();let aiCalls=0,lastPrompt='';const visual={updatedAt:'2026-10-10',consolidatedInventory:[{room:'Lobby',visibleName:'Door',quantity:2,evidenceSweepIds:['real-sweep']}]};
const bucket={put:async(k,v,options)=>{stored.set(k,typeof v==='string'?v:await new Response(v).arrayBuffer());meta.set(k,options?.customMetadata||{})},get:async k=>{const v=stored.get(k);return v===undefined?null:{body:v,json:async()=>JSON.parse(v)}},list:async({prefix,limit})=>({objects:[...stored.keys()].filter(k=>k.startsWith(prefix)).sort().slice(0,limit||1000).map(key=>({key,customMetadata:meta.get(key)})),truncated:false})};
const ctx={Response,Request,URL,crypto,console,process:{env:{}},File,FormData,loadPersistedVisualEvidence:async()=>visual,loadPersistedGeometryEvidence:async()=>({objPresent:true}),loadGeometryAnalysis:async()=>({algorithmVersion:'test-geometry'}),fetch:async(u,init)=>{aiCalls++;lastPrompt=JSON.parse(init.body).input[0].content[0].text;return Response.json({output_text:JSON.stringify({summary:'Test report',limitations:['Verify'],rows:[{cells:['Lobby','Door','2','Count','OBJ','Verify'],classification:'OBSERVED',confidence:80,evidenceSweepIds:['real-sweep','fake-sweep']}]})})}};vm.createContext(ctx);vm.runInContext(stripTypeScriptTypes(src),ctx);const {appWorker,REPORTS,BUILDINGS}=ctx.test,env={BUILDING_DATA:bucket,OPENAI_API_KEY:'test',MATTERPORT_SDK_KEY:'test'};
function scripts(html){for(const m of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1])}
async function page(path){const r=await appWorker.fetch(new Request('https://example.com'+path),env);assert.equal(r.status,200,path);const html=await r.text();scripts(html);assert(html.includes('aria-label="Breadcrumb"'));const links=[...html.matchAll(/<a[^>]*href="([^"]*\/ingest|\/evidence\/update)"[^>]*>/g)];assert.equal(links.length,1,path+' footer-only update link');assert(html.indexOf(links[0][0])>html.indexOf('<footer'));return html}
require('node:test')('building report library workflow', async()=>{
assert.equal(REPORTS.length,11);assert(REPORTS.some(r=>r.slug==='facility-inspection'));assert(REPORTS.some(r=>r.slug==='cost-segregation'));await page('/');for(const slug of ['crc','bell','vues']){const landing=await page('/'+slug);assert(landing.includes('Ask Building GPT'));assert(!landing.includes('Ask GBI'));await page('/'+slug+'/evidence');const ingest=await page('/'+slug+'/ingest');assert(ingest.includes('clientRecordsForm'));assert(!ingest.includes('id="floorPlanImg"'));const generator=await page('/'+slug+'/reports');assert(generator.includes('Create only the reports you need'));for(const def of REPORTS){const html=await page('/'+slug+'/reports/'+def.slug);assert(html.includes('method:regenerate?"POST":"GET"'));assert(html.includes('history.replaceState'));assert(!html.includes('<h2>Evidence library'));}}
assert.equal(aiCalls,0,'Opening pages never generates reports');
let r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/quantity-takeoff'),env);assert.equal(r.status,404);
const data=new FormData();data.set('title','Original drawings');data.set('source','Owner');data.set('summary','Door was replaced in 2024.');data.set('file',new File(['PDF bytes'],'drawing.pdf',{type:'application/pdf'}));r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/client-records',{method:'POST',body:data}),env);assert.equal(r.status,201);const upload=await r.json();
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/quantity-takeoff',{method:'POST'}),env);assert.equal(r.status,201);const one=(await r.json()).study;assert.equal(aiCalls,1);assert(lastPrompt.includes('Door was replaced in 2024'));assert(lastPrompt.includes('contentsNotExtracted'));assert.deepEqual(one.rows[0].evidenceSweepIds,['real-sweep']);assert.equal(one.evidenceBasis.clientRecordIds.length,1);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/quantity-takeoff'),env);assert.equal((await r.json()).study.versionId,one.versionId);assert.equal(aiCalls,1,'GET reuses saved report');
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/quantity-takeoff',{method:'POST'}),env);assert.equal(r.status,201);const two=(await r.json()).study;assert.notEqual(one.versionId,two.versionId);r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports'),env);assert.equal((await r.json()).versions.length,2);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/reports/quantity-takeoff?version='+one.versionId),env);assert.equal((await r.json()).study.versionId,one.versionId);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-002/reports/quantity-takeoff?version='+one.versionId),env);assert.equal(r.status,404);
r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-001/client-records/'+upload.id+'/file'),env);assert.equal(r.status,200);assert.equal(await r.text(),'PDF bytes');r=await appWorker.fetch(new Request('https://example.com/api/buildings/BLDG-002/client-records/'+upload.id+'/file'),env);assert.equal(r.status,404);
r=await appWorker.fetch(new Request('https://example.com/crc/cost-seg'),env);assert.equal(r.status,302);assert(r.headers.get('location').endsWith('/crc/reports/cost-segregation'));
async function browserLoad(searchString,mode){
 const elements={};const elem=id=>elements[id]??={textContent:'',innerHTML:'',value:'',rows:[],addEventListener(){},querySelectorAll:()=>[]};let posts=0,gets=0,replaced=false;
 const context={document:{getElementById:elem,querySelectorAll:()=>[]},window:{},location:{search:searchString,pathname:'/crc/reports/quantity-takeoff'},history:{replaceState(){replaced=true}},URLSearchParams,URL,Blob,Intl,Set,AbortController,Date,setInterval:()=>1,clearInterval(){},setTimeout:()=>1,clearTimeout(){},fetch:async(u,init)=>{if(u.endsWith('/evidence'))return Response.json({visualInventory:visual});if(init?.method==='POST'){posts++;return Response.json({study:two})}gets++;return mode==='empty'?Response.json({error:'No saved report'},{status:404}):Response.json({study:one})}};
 const html=ctx.test.reportWorkspaceHtml(BUILDINGS['BLDG-001'],REPORTS.find(d=>d.slug==='quantity-takeoff'),'test');const script=html.match(/<script type="module">([\s\S]*?)<\/script>/)[1].replace('load(createRequested);','globalThis.pending=load(createRequested);');vm.createContext(context);vm.runInContext(script,context);await context.pending;
 return {posts,gets,replaced,elements};
}
const cached=await browserLoad('','saved');assert.equal(cached.posts,0);assert.equal(cached.gets,1);assert(cached.elements.adjusterRows.innerHTML.includes('Lobby'));const empty=await browserLoad('','empty');assert.equal(empty.posts,0);assert(empty.elements.statusText.textContent.includes('No report saved'));const created=await browserLoad('?create=1','saved');assert.equal(created.posts,1);assert.equal(created.gets,0);assert(created.replaced);console.log('PASS: browser flow loads saved reports without generation, leaves empty workspaces idle, creates only explicitly selected report, and removes create flag before refresh.');
console.log('PASS: all 3 buildings and 11 report workspaces, generated scripts, footer-only updates, on-demand generation, saved report reuse, version retention, building isolation, client file/summary persistence and evidence provenance.');});
