const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),{stripTypeScriptTypes}=require('node:module');
const geometrySrc=fs.readFileSync(path.join(__dirname,'../worker/geometry-analysis.ts'),'utf8').replace(/export /g,'');const geometry={};vm.createContext(geometry);vm.runInContext(stripTypeScriptTypes(geometrySrc)+';globalThis.detect=detectRoundTableCandidates;',geometry);
const indexSrc=fs.readFileSync(path.join(__dirname,'../worker/index.ts'),'utf8').replace(/^import .*;$/gm,'').replace('export default appWorker;','globalThis.link=applyGeometryAssetDimensions;');const index={};vm.createContext(index);vm.runInContext(stripTypeScriptTypes(indexSrc),index);
require('node:test')('OBJ round tabletop dimensions link to inventory without replacing client measurements',()=>{
 const vertices=[],faces=[];function vertex(x,y,z){const id=vertices.length/3;vertices.push(x,y,z);return id}function disc(x,y,z,r){const center=vertex(x,y,z),ring=[];for(let j=0;j<96;j++){const t=2*Math.PI*j/96;ring.push(vertex(x+r*Math.cos(t),y+r*Math.sin(t),z))}for(let j=0;j<96;j++)faces.push(center,ring[j],ring[(j+1)%96]);}
 disc(0,0,.76,.75);disc(3,0,.76,.75);disc(6,0,.76,.75);disc(0,5,0,.75); // Floor surfaces must not become table candidates.
 const square=[vertex(10,0,.76),vertex(11.5,0,.76),vertex(11.5,1.5,.76),vertex(10,1.5,.76)];faces.push(square[0],square[1],square[2],square[0],square[2],square[3]);
 const candidates=geometry.detect(vertices,faces,[0]);assert.equal(candidates.length,3,'Round tables counted once; floor and square countertop excluded');for(const c of candidates)assert(Math.abs(c.diameterFt-1.5*3.280839895)<.35,'Mesh-derived diameter within raster resolution');
 const analysis={sourceObjKey:'building.obj',analyzedAt:'2026-10-10',spatialObjects:{roundTableCandidates:candidates}};
 const asset={id:'INV-TABLE',name:'Round banquet tables',quantity:24,length:null,width:null,height:null,scanEvidence:{spatialAnchors:[]}};const linked=index.link([asset],analysis)[0];assert(linked.diameter>4.5&&linked.diameter<5.3);assert.equal(linked.quantity,24,'Geometry candidates do not replace authoritative inventory count');assert.equal(linked.dimensionConfidence,65);assert.equal(linked.geometryDimensionEvidence.sourceObjKey,'building.obj');assert.equal(linked.geometryDimensionEvidence.candidateIds.length,3);assert.equal(linked.geometryDimensionEvidence.association,'visual class + dominant mesh size');
 const measured={id:'CLIENT-TABLE',name:'Round banquet tables',diameter:6,dimensionSource:'Owner tape measurement'};index.link([measured],analysis);assert.equal(measured.diameter,6,'Client measurements retain priority');
 const unrelated={name:'Rectangular tables',quantity:10};index.link([unrelated],analysis);assert.equal(unrelated.diameter,undefined,'Round mesh results cannot label rectangular assets');
 const insufficient={name:'Round banquet tables',quantity:24};index.link([insufficient],{spatialObjects:{roundTableCandidates:candidates.slice(0,1)}});assert.equal(insufficient.diameter,undefined,'One unanchored surface cannot establish class dimensions');
 const nearby={name:'Round banquet tables',quantity:24,scanEvidence:{spatialAnchors:[{x:0,y:0,z:1}]}};index.link([nearby],analysis);assert.equal(nearby.geometryDimensionEvidence.association,'spatial proximity');
});
